"""change_approved_to_status

Revision ID: 47481498c3df
Revises: 1882c7ca9d14
Create Date: 2025-06-24 19:52:12.041520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47481498c3df'
down_revision: Union[str, Sequence[str], None] = '1882c7ca9d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('status', sa.Enum('WAITING', 'PUBLISHED', 'DECLINED', name='poststatus'), nullable=True))
    op.drop_column('posts', 'approved')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('approved', sa.BOOLEAN(), nullable=True))
    op.drop_column('posts', 'status')
    # ### end Alembic commands ###
